<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CFXML [
            <!ELEMENT CFXML (thisDocumentGenerationDateTime,thisDocumentIdentifier,CFData)>
            <!ELEMENT thisDocumentGenerationDateTime (DateTimeStamp)>
            <!ELEMENT thisDocumentIdentifier (ProprietaryDocumentIdentifier)>
            <!ELEMENT CFData (ProprietaryInformation*,ProprietaryShippingInformation?,ProductLineItem+,CFReportBLOB?)>
            <!ELEMENT ProprietaryShippingInformation (Name, FinancialAmount)>
            <!ELEMENT ShippingUnitListPrice (FinancialAmount, PriceTerm)>
            <!ELEMENT DateTimeStamp (#PCDATA)>
            <!ELEMENT ProprietaryDocumentIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryInformation (Name,Value)>
            <!ELEMENT ProductLineItem (  ProductLineNumber , TransactionType , CPUSIUvalue , ConfigurationControlNumber?, ProprietaryGroupIdentifier , ServicePacLineNumberReference? , Quantity  , ProductIdentification , UnitListPrice? , ShippingUnitListPrice? , MaintenanceUnitListPrice? , ProductSubLineItem* ) >
            <!ELEMENT CFReportBLOB  (#PCDATA)>
            <!ELEMENT Name  (#PCDATA)>
            <!ELEMENT Value (#PCDATA)>
            <!ELEMENT CPUSIUvalue (#PCDATA)>
            <!ELEMENT ConfigurationControlNumber (#PCDATA)>
            <!ELEMENT ProductLineNumber (#PCDATA)>
            <!ELEMENT ProprietaryGroupIdentifier (#PCDATA)>
            <!ELEMENT ServicePacLineNumberReference (#PCDATA)>
            <!ELEMENT Quantity (#PCDATA)>
            <!ELEMENT TransactionType (#PCDATA)>
            <!ELEMENT ProductIdentification (PartnerProductIdentification*) >
            <!ELEMENT ProductSubLineItem ( LineNumber, TransactionType, Quantity , ExchangeAddSubLineItemNumber? , ProductIdentification, UnitListPrice?,MaintenanceUnitListPrice?)>
            <!ELEMENT UnitListPrice ( FinancialAmount, PriceTerm)>
            <!ELEMENT MaintenanceUnitListPrice (FinancialAmount, PriceTerm)>
            <!ELEMENT PartnerProductIdentification ( OrderedProductIdentifier?, ProprietaryProductIdentifier, ProductDescription?, ProductTypeCode?, ProductIdentifierTypeCode?) >
            <!ELEMENT LineNumber (#PCDATA)>
            <!ELEMENT ExchangeAddSubLineItemNumber (#PCDATA)>
            <!ELEMENT FinancialAmount ( GlobalCurrencyCode, MonetaryAmount )>
            <!ELEMENT PriceTerm (#PCDATA)>
            <!ELEMENT OrderedProductIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryProductIdentifier (#PCDATA)>
            <!ELEMENT ProductDescription (#PCDATA)>
            <!ELEMENT ProductTypeCode (#PCDATA)>
            <!ELEMENT ProductIdentifierTypeCode (#PCDATA)>
            <!ELEMENT GlobalCurrencyCode (#PCDATA)>
            <!ELEMENT MonetaryAmount (#PCDATA)>
            
]>
<CFXML>
  <thisDocumentGenerationDateTime>
    <DateTimeStamp>02:37:47</DateTimeStamp>
  </thisDocumentGenerationDateTime>
  <thisDocumentIdentifier>
    <ProprietaryDocumentIdentifier>CFXML.1.2025-05-09T00:00:00+00:00</ProprietaryDocumentIdentifier>
  </thisDocumentIdentifier>
  <CFData>
    <ProprietaryInformation>
      <Name>CFXML</Name>
      <Value>1.0</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Configurator Identifier</Name>
      <Value>ECMPWR.90501a251073</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Price File Date</Name>
      <Value>2025-05-09</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Checksum</Name>
      <Value>2720346566</Value>
    </ProprietaryInformation>
    <ProprietaryShippingInformation>
      <Name>Total Non-discountable Shipping and Handling Charge</Name>
      <FinancialAmount>
        <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
        <MonetaryAmount>8,372.56</MonetaryAmount>
      </FinancialAmount>
    </ProprietaryShippingInformation>
    <ProductLineItem>
      <ProductLineNumber>1000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>1</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>9043-MRX</ProprietaryProductIdentifier>
          <ProductDescription>Server 1:Server 1:9043 Model MRX</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>265,131.6</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ShippingUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>2,215.61</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </ShippingUnitListPrice>
      <ProductSubLineItem>
        <LineNumber>1001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>0265</ProprietaryProductIdentifier>
            <ProductDescription>AIX Partition Specify</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>2146</ProprietaryProductIdentifier>
            <ProductDescription>Primary OS - AIX</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1003</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>4</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>4558</ProprietaryProductIdentifier>
            <ProductDescription>Power Cord To PDU/UPS, (100-240V/16A)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>93.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1004</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>4649</ProprietaryProductIdentifier>
            <ProductDescription>Rack Integration Services</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>1,005.3</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1005</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>4651</ProprietaryProductIdentifier>
            <ProductDescription>Rack Indicator, Rack #1</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1006</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>5000</ProprietaryProductIdentifier>
            <ProductDescription>Software Preload Required</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1007</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>6577</ProprietaryProductIdentifier>
            <ProductDescription>Power Cable - Drawer to IBM PDU, 200-240V/10A</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>93.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1008</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>26</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9440</ProprietaryProductIdentifier>
            <ProductDescription>New AIX License Core Counter</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1009</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9716</ProprietaryProductIdentifier>
            <ProductDescription>Language Group Specify - Korean</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1010</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AKNC</ProprietaryProductIdentifier>
            <ProductDescription>Premium S&amp;H Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1011</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>4</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EB39</ProprietaryProductIdentifier>
            <ProductDescription>Power Supply - 2300W for Server (200-240 VAC)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>8,042.3</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1012</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>12</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EB46</ProprietaryProductIdentifier>
            <ProductDescription>10GbE Optical Transceiver SFP+ SR</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>368.8</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1013</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>6</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EC72</ProprietaryProductIdentifier>
            <ProductDescription>PCIe4 2-Port 25/10/1 GbE RoCE SFP28 Adapter</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>13,118.6</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1014</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>8</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EC7T</ProprietaryProductIdentifier>
            <ProductDescription>800GB Mainstream NVMe U.2 SSD 4k for AIX/Linux</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>8,705.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1015</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ECLS</ProprietaryProductIdentifier>
            <ProductDescription>3.0M CXP x16 Copper Cable Pair for PCIe4 Expansion Drawer</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>6,031.7</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1016</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>6</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ECW0</ProprietaryProductIdentifier>
            <ProductDescription>Optical Wrap Plug</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>67.2</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1017</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EHSD</ProprietaryProductIdentifier>
            <ProductDescription>Power AIX Segment Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1018</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EJ0Q</ProprietaryProductIdentifier>
            <ProductDescription>Storage NVMe Backplan</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1019</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EJ2A</ProprietaryProductIdentifier>
            <ProductDescription>PCIe4 x16 to CXP Converter Adapter (support AOC)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>11,728.4</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1020</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EMCD</ProprietaryProductIdentifier>
            <ProductDescription>512 of #EMCA 1GB Memory Activations for MRX</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>83,825</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1021</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>12</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EMFH</ProprietaryProductIdentifier>
            <ProductDescription>64GB (2 x 32GB) DDR5 Memory DDIMM</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>40,201.7</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1022</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>6</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EN1L</ProprietaryProductIdentifier>
            <ProductDescription>PCIe4 32Gb 4-port Optical Fibre Channel Adapter</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>52,938</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1023</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ENZ0</ProprietaryProductIdentifier>
            <ProductDescription>PCIe Gen4 I/O Expansion Drawer</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>39,371.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1024</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ENZF</ProprietaryProductIdentifier>
            <ProductDescription>PCIe4 6-Slot Fanout Module for PCIe Gen4 I/O Expansion Drawer</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>37,731.1</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1025</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>4</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EPEU</ProprietaryProductIdentifier>
            <ProductDescription>12-core Typical 3.35 to 4.0 GHZ (max) processor</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>135,913.4</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1026</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EPLU</ProprietaryProductIdentifier>
            <ProductDescription>Front Heatsink + TIM PAD (For MRX)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>3,351</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1027</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>EPLV</ProprietaryProductIdentifier>
            <ProductDescription>Rear Heatsink + TIM PAD (For MRX)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>