<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CFXML [
            <!ELEMENT CFXML (thisDocumentGenerationDateTime,thisDocumentIdentifier,CFData)>
            <!ELEMENT thisDocumentGenerationDateTime (DateTimeStamp)>
            <!ELEMENT thisDocumentIdentifier (ProprietaryDocumentIdentifier)>
            <!ELEMENT CFData (ProprietaryInformation*,ProprietaryShippingInformation?,ProductLineItem+,CFReportBLOB?)>
            <!ELEMENT ProprietaryShippingInformation (Name, FinancialAmount)>
            <!ELEMENT ShippingUnitListPrice (FinancialAmount, PriceTerm)>
            <!ELEMENT DateTimeStamp (#PCDATA)>
            <!ELEMENT ProprietaryDocumentIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryInformation (Name,Value)>
            <!ELEMENT ProductLineItem (  ProductLineNumber , TransactionType , CPUSIUvalue , ConfigurationControlNumber?, ProprietaryGroupIdentifier , ServicePacLineNumberReference? , Quantity  , ProductIdentification , UnitListPrice? , ShippingUnitListPrice? , MaintenanceUnitListPrice? , ProductSubLineItem* ) >
            <!ELEMENT CFReportBLOB  (#PCDATA)>
            <!ELEMENT Name  (#PCDATA)>
            <!ELEMENT Value (#PCDATA)>
            <!ELEMENT CPUSIUvalue (#PCDATA)>
            <!ELEMENT ConfigurationControlNumber (#PCDATA)>
            <!ELEMENT ProductLineNumber (#PCDATA)>
            <!ELEMENT ProprietaryGroupIdentifier (#PCDATA)>
            <!ELEMENT ServicePacLineNumberReference (#PCDATA)>
            <!ELEMENT Quantity (#PCDATA)>
            <!ELEMENT TransactionType (#PCDATA)>
            <!ELEMENT ProductIdentification (PartnerProductIdentification*) >
            <!ELEMENT ProductSubLineItem ( LineNumber, TransactionType, Quantity , ExchangeAddSubLineItemNumber? , ProductIdentification, UnitListPrice?,MaintenanceUnitListPrice?)>
            <!ELEMENT UnitListPrice ( FinancialAmount, PriceTerm)>
            <!ELEMENT MaintenanceUnitListPrice (FinancialAmount, PriceTerm)>
            <!ELEMENT PartnerProductIdentification ( OrderedProductIdentifier?, ProprietaryProductIdentifier, ProductDescription?, ProductTypeCode?, ProductIdentifierTypeCode?) >
            <!ELEMENT LineNumber (#PCDATA)>
            <!ELEMENT ExchangeAddSubLineItemNumber (#PCDATA)>
            <!ELEMENT FinancialAmount ( GlobalCurrencyCode, MonetaryAmount )>
            <!ELEMENT PriceTerm (#PCDATA)>
            <!ELEMENT OrderedProductIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryProductIdentifier (#PCDATA)>
            <!ELEMENT ProductDescription (#PCDATA)>
            <!ELEMENT ProductTypeCode (#PCDATA)>
            <!ELEMENT ProductIdentifierTypeCode (#PCDATA)>
            <!ELEMENT GlobalCurrencyCode (#PCDATA)>
            <!ELEMENT MonetaryAmount (#PCDATA)>
            
]>
<CFXML>
  <thisDocumentGenerationDateTime>
    <DateTimeStamp>10:07:57</DateTimeStamp>
  </thisDocumentGenerationDateTime>
  <thisDocumentIdentifier>
    <ProprietaryDocumentIdentifier>CFXML.20250404_TS4300_LTO8 HH 6EA_Cleaning 6EA_media 20EA.2025-04-03T00:00:00+00:00</ProprietaryDocumentIdentifier>
  </thisDocumentIdentifier>
  <CFData>
    <ProprietaryInformation>
      <Name>CFXML</Name>
      <Value>1.0</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Configurator Identifier</Name>
      <Value>ECMSSD.90501a250870</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Price File Date</Name>
      <Value>2025-04-04</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Checksum</Name>
      <Value>3386390122</Value>
    </ProprietaryInformation>
    <ProprietaryShippingInformation>
      <Name>Total Non-discountable Shipping and Handling Charge</Name>
      <FinancialAmount>
        <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
        <MonetaryAmount>869.99</MonetaryAmount>
      </FinancialAmount>
    </ProprietaryShippingInformation>
    <ProductLineItem>
      <ProductLineNumber>1000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>3555-E3A</ProprietaryProductIdentifier>
          <ProductDescription>No CPUSIU for the following products:TS4300 Tape Expansion Module</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>20,968.4</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ShippingUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>383.65</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </ShippingUnitListPrice>
      <MaintenanceUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>472</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>Y</PriceTerm>
      </MaintenanceUnitListPrice>
      <ProductSubLineItem>
        <LineNumber>1001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>1899</ProprietaryProductIdentifier>
            <ProductDescription>First Power Supply</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>3,092.3</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>1900</ProprietaryProductIdentifier>
            <ProductDescription>Additional Power Supply</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>3,092.3</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1003</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>7002</ProprietaryProductIdentifier>
            <ProductDescription>Rack Mount Kit</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>1,611.1</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1004</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9844</ProprietaryProductIdentifier>
            <ProductDescription>2.8M Power Cord 250V Korea</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>64.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1005</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9848</ProprietaryProductIdentifier>
            <ProductDescription>Rack to PDU line cord</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>64.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1006</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9906</ProprietaryProductIdentifier>
            <ProductDescription>New order install</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1007</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>3</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AGK2</ProprietaryProductIdentifier>
            <ProductDescription>25 meter OM3 fiber Cable (LC)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>322.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1008</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>3</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AGKM</ProprietaryProductIdentifier>
            <ProductDescription>LTO 8 HH Fibre channel drive</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>26,540.4</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1009</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AKNC</ProprietaryProductIdentifier>
            <ProductDescription>Premium S&amp;H Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>2000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>2000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>3555-L3A</ProprietaryProductIdentifier>
          <ProductDescription>No CPUSIU for the following products:TS4300 Tape Base Module</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>23,706.1</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ShippingUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>383.65</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </ShippingUnitListPrice>
      <MaintenanceUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>850</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>Y</PriceTerm>
      </MaintenanceUnitListPrice>
      <ProductSubLineItem>
        <LineNumber>2001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>1411</ProprietaryProductIdentifier>
            <ProductDescription>Fibre Tape Drive Wrap Tool</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>870.4</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>1900</ProprietaryProductIdentifier>
            <ProductDescription>Additional Power Supply</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>3,092.3</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2003</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>7002</ProprietaryProductIdentifier>
            <ProductDescription>Rack Mount Kit</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>1,611.1</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2004</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9002</ProprietaryProductIdentifier>
            <ProductDescription>First Expansion unit</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2005</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9600</ProprietaryProductIdentifier>
            <ProductDescription>Attached to IBM AIX System</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2006</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9848</ProprietaryProductIdentifier>
            <ProductDescription>Rack to PDU line cord</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>64.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2007</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>3</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AGK2</ProprietaryProductIdentifier>
            <ProductDescription>25 meter OM3 fiber Cable (LC)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>322.9</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2008</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>3</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AGKM</ProprietaryProductIdentifier>
            <ProductDescription>LTO 8 HH Fibre channel drive</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>26,540.4</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2009</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AGL0</ProprietaryProductIdentifier>
            <ProductDescription>GEN-3 Base Module</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>2010</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AKNC</ProprietaryProductIdentifier>
            <ProductDescription>Premium S&amp;H Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>3000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>3000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>3589-004</ProprietaryProductIdentifier>
          <ProductDescription>No CPUSIU for the following products:Ultrium cleaning cartridges</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>0</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ShippingUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>51.34</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </ShippingUnitListPrice>
      <ProductSubLineItem>
        <LineNumber>3001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>4001</ProprietaryProductIdentifier>
            <ProductDescription>Ultrium Single Cleaning Cartridge</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>288</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>3002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>4005</ProprietaryProductIdentifier>
            <ProductDescription>5-pack Ultrium cleaning cartridge</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>1,439.6</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>3003</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AKNC</ProprietaryProductIdentifier>
            <ProductDescription>Premium S&amp;H Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>4000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>4000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>3589-552</ProprietaryProductIdentifier>
          <ProductDescription>No CPUSIU for the following products:12 TB Ultrium 8 Tape Cartridge 20-pack Labeled</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>0</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ShippingUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>51.34</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </ShippingUnitListPrice>
      <ProductSubLineItem>
        <LineNumber>4001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>