<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CFXML [
            <!ELEMENT CFXML (thisDocumentGenerationDateTime,thisDocumentIdentifier,CFData)>
            <!ELEMENT thisDocumentGenerationDateTime (DateTimeStamp)>
            <!ELEMENT thisDocumentIdentifier (ProprietaryDocumentIdentifier)>
            <!ELEMENT CFData (ProprietaryInformation*,ProprietaryShippingInformation?,ProductLineItem+,CFReportBLOB?)>
            <!ELEMENT ProprietaryShippingInformation (Name, FinancialAmount)>
            <!ELEMENT ShippingUnitListPrice (FinancialAmount, PriceTerm)>
            <!ELEMENT DateTimeStamp (#PCDATA)>
            <!ELEMENT ProprietaryDocumentIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryInformation (Name,Value)>
            <!ELEMENT ProductLineItem (  ProductLineNumber , TransactionType , CPUSIUvalue , ConfigurationControlNumber?, ProprietaryGroupIdentifier , ServicePacLineNumberReference? , Quantity  , ProductIdentification , UnitListPrice? , ShippingUnitListPrice? , MaintenanceUnitListPrice? , ProductSubLineItem* ) >
            <!ELEMENT CFReportBLOB  (#PCDATA)>
            <!ELEMENT Name  (#PCDATA)>
            <!ELEMENT Value (#PCDATA)>
            <!ELEMENT CPUSIUvalue (#PCDATA)>
            <!ELEMENT ConfigurationControlNumber (#PCDATA)>
            <!ELEMENT ProductLineNumber (#PCDATA)>
            <!ELEMENT ProprietaryGroupIdentifier (#PCDATA)>
            <!ELEMENT ServicePacLineNumberReference (#PCDATA)>
            <!ELEMENT Quantity (#PCDATA)>
            <!ELEMENT TransactionType (#PCDATA)>
            <!ELEMENT ProductIdentification (PartnerProductIdentification*) >
            <!ELEMENT ProductSubLineItem ( LineNumber, TransactionType, Quantity , ExchangeAddSubLineItemNumber? , ProductIdentification, UnitListPrice?,MaintenanceUnitListPrice?)>
            <!ELEMENT UnitListPrice ( FinancialAmount, PriceTerm)>
            <!ELEMENT MaintenanceUnitListPrice (FinancialAmount, PriceTerm)>
            <!ELEMENT PartnerProductIdentification ( OrderedProductIdentifier?, ProprietaryProductIdentifier, ProductDescription?, ProductTypeCode?, ProductIdentifierTypeCode?) >
            <!ELEMENT LineNumber (#PCDATA)>
            <!ELEMENT ExchangeAddSubLineItemNumber (#PCDATA)>
            <!ELEMENT FinancialAmount ( GlobalCurrencyCode, MonetaryAmount )>
            <!ELEMENT PriceTerm (#PCDATA)>
            <!ELEMENT OrderedProductIdentifier (#PCDATA)>
            <!ELEMENT ProprietaryProductIdentifier (#PCDATA)>
            <!ELEMENT ProductDescription (#PCDATA)>
            <!ELEMENT ProductTypeCode (#PCDATA)>
            <!ELEMENT ProductIdentifierTypeCode (#PCDATA)>
            <!ELEMENT GlobalCurrencyCode (#PCDATA)>
            <!ELEMENT MonetaryAmount (#PCDATA)>
            
]>
<CFXML>
  <thisDocumentGenerationDateTime>
    <DateTimeStamp>14:36:59</DateTimeStamp>
  </thisDocumentGenerationDateTime>
  <thisDocumentIdentifier>
    <ProprietaryDocumentIdentifier>CFXML.FS7300_1.5TB_7.68TB 9ea_32G 16port_구성파일_250305.2025-03-04T00:00:00+00:00</ProprietaryDocumentIdentifier>
  </thisDocumentIdentifier>
  <CFData>
    <ProprietaryInformation>
      <Name>CFXML</Name>
      <Value>1.0</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Configurator Identifier</Name>
      <Value>ECMSSD.90501a250550</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Price File Date</Name>
      <Value>2025-03-05</Value>
    </ProprietaryInformation>
    <ProprietaryInformation>
      <Name>Checksum</Name>
      <Value>3811517307</Value>
    </ProprietaryInformation>
    <ProprietaryShippingInformation>
      <Name>Total Non-discountable Shipping and Handling Charge</Name>
      <FinancialAmount>
        <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
        <MonetaryAmount>678.86</MonetaryAmount>
      </FinancialAmount>
    </ProprietaryShippingInformation>
    <ProductLineItem>
      <ProductLineNumber>1000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>1</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>4657-924</ProprietaryProductIdentifier>
          <ProductDescription>4657-924 #1:IBM FlashSystem 7300 NVMe Control Enclosure</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>314,047.9</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ShippingUnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>678.86</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </ShippingUnitListPrice>
      <ProductSubLineItem>
        <LineNumber>1001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>9730</ProprietaryProductIdentifier>
            <ProductDescription>Power Cord - PDU Connection</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>98.1</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1002</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ACGB</ProprietaryProductIdentifier>
            <ProductDescription>768 GB Cache upgrade</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>59,034.5</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1003</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ACGJ</ProprietaryProductIdentifier>
            <ProductDescription>512 GB Cache upgrade</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>39,378.6</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1004</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ACGV</ProprietaryProductIdentifier>
            <ProductDescription>240 GB M.2 Boot drive Pair</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1005</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>16</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ACSR</ProprietaryProductIdentifier>
            <ProductDescription>5m OM3 Fiber Cable (LC)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>219.7</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1006</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>2</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ADBE</ProprietaryProductIdentifier>
            <ProductDescription>32 Gb FC 4 Port Adapter Cards (Pair)</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>25,329.3</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1007</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ADN1</ProprietaryProductIdentifier>
            <ProductDescription>Order Type 1 Indicator - CTO</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1008</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>9</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ADT4</ProprietaryProductIdentifier>
            <ProductDescription>7.68 TB NVMe Flash Drive</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>26,550.2</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1009</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AHZE</ProprietaryProductIdentifier>
            <ProductDescription>Hybrid Flash Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1010</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>AKNC</ProprietaryProductIdentifier>
            <ProductDescription>Premium S&amp;H Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>0</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1011</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ALH0</ProprietaryProductIdentifier>
            <ProductDescription>Expert Care Indicator</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
      <ProductSubLineItem>
        <LineNumber>1012</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>ALK3</ProprietaryProductIdentifier>
            <ProductDescription>EC Advanced 3 Year</ProductDescription>
            <ProductTypeCode>Hardware</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>2000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>4658-A03</ProprietaryProductIdentifier>
          <ProductDescription>4657-924 #1:3 year IBM Storage Expert Care Advanced</ProductDescription>
          <ProductTypeCode>Hardware</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>116,437.98</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
    </ProductLineItem>
    <ProductLineItem>
      <ProductLineNumber>3000</ProductLineNumber>
      <TransactionType>NEW</TransactionType>
      <CPUSIUvalue>0</CPUSIUvalue>
      <ProprietaryGroupIdentifier>1000</ProprietaryGroupIdentifier>
      <Quantity>1</Quantity>
      <ProductIdentification>
        <PartnerProductIdentification>
          <OrderedProductIdentifier>N/A</OrderedProductIdentifier>
          <ProprietaryProductIdentifier>5773-STG</ProprietaryProductIdentifier>
          <ProductDescription>Support Line for Storage - 3 Year</ProductDescription>
          <ProductTypeCode>Software</ProductTypeCode>
          <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
        </PartnerProductIdentification>
      </ProductIdentification>
      <UnitListPrice>
        <FinancialAmount>
          <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
          <MonetaryAmount>N/C</MonetaryAmount>
        </FinancialAmount>
        <PriceTerm>0</PriceTerm>
      </UnitListPrice>
      <ProductSubLineItem>
        <LineNumber>3001</LineNumber>
        <TransactionType>ADD</TransactionType>
        <Quantity>1</Quantity>
        <ProductIdentification>
          <PartnerProductIdentification>
            <OrderedProductIdentifier></OrderedProductIdentifier>
            <ProprietaryProductIdentifier>2000</ProprietaryProductIdentifier>
            <ProductDescription>Support per Server (N/C)</ProductDescription>
            <ProductTypeCode>Software</ProductTypeCode>
            <ProductIdentifierTypeCode>MTM-FC</ProductIdentifierTypeCode>
          </PartnerProductIdentification>
        </ProductIdentification>
        <UnitListPrice>
          <FinancialAmount>
            <GlobalCurrencyCode>KWON</GlobalCurrencyCode>
            <MonetaryAmount>N/C</MonetaryAmount>
          </FinancialAmount>
          <PriceTerm>0</PriceTerm>
        </UnitListPrice>
      </ProductSubLineItem>
    </ProductLineItem>
    <CFReportBLOB><![CDATA[
003120250304ECMSSD  90501a250550AP7660023                                                                                                   KRko                     00                                                                                                                                                
030Unclassified          
05         00                                                               
05         00   Configuration ID: GG82PN12MN6WL000000   CEID: 10ailnjz
05         10                                                               
05         10   Created on We Mar 05 2025 14:36:59 GMT+0900 (UTC) by Sang In
05         00   Park                                                        
05         10                                                               
05         1U   You have selected IBM Storage Expert Care for your Client.  
05         1U   Note: Only in enclosed city list and <50 KM of CBD, 24/48/72
05         0U   hours committed fix can be sold without additional delivery 
05         0U   approval.                                                   
05         10   Customer Requested Arrival Date: 2025/03/19                 
061041001MDDIBM_INC_SHIPPING^1^YES^IBM_WITHDRAWN_PRODUCTS_MODE^1^FALSE^IBM_REDUCED_SEV_MSG_MS^2^sw_577x_cognitive_proactive_must_read_message^sw_5608_pc2_minimum_quantity_rule_must_read_message^IBM_FV_VISIBLE^1^FALSE^IBM_CRAD^1^19010102^SV_DEFAULT_CATEGORIES^0^SW_Global_06_swrs_cho_global_preference_control^1^sw_core_otc_charge_option^SW_Global_06_swrs_media_global_preference_control^1^swn_esd_media^SW_Global_06_swrs_language_global_preference_control^1^sw_core_language_prim_korean^SW_Global_06_swrs_maintenance_global_preference_control^1^sw_core_nim_maint_3yr^SW_Global_06_swrs_shipping_options_global_control^1^sw_core_shipping_option_3444^SW_Global_06_swrs_expedite_global_control^1^sw_core_shipping_option_no_expedite^SW_Global_06_swrs_suppress_global_control^1^sw_core_shipping_option_not_3480^SW_Global_06_swrs_preinstall_languages_control^1^sw_core_preinst_language_korean^SW_Global_06_swrs_cultural_languages_control^1^sw_core_cultural_std_language^SW_Global_06_swrs_support_global_preference_control^1^sw_9by5_support_service^
07   4657-924 #1                                     4657924                         
011INITIAL ORDER CONFIGURATION                                                       
060979001MDDIBM_PLATFORM^1^All^SW_MODEL^2^^pSeries or RS^SW_TYPE^1^All^SWN_PROCESSED_SOFTWARE_OBJECTS_KEY_S^6^sw_5773_stg_fs5200_default_and_require_provider_group^sw_5765_vcc_default_linux_server_editions_provider_group^sw_5765_cmt_default_on_selected_hw_editions_provider_group^sw_5639_xce_on_p10_default_editions_provider_group^sw_5765_vc2_default_editions_provider_group^sw_5639_rle_f01_f06_non_hpc_solution_default_editions_provider_group^SWN_CATEGORIES_MC^2^ibm_sw_core_category_management^ibm_sw_core_category_otherstorage^sw_rs_5608_pc2:new_maintenance^1^three_year_registration^sw_rs_5608_pc2:existing_maintenance^1^swn_maint_not_applicable^SWN_CONTEXT_SOFTWARE_OBJECTS_KEY_S^1^ibm_all_platform_type:All::DEFAULT:{}:FALSE:DEFAULT:{}:DEFAULT:DEFAULT:::FALSE:0:_:DEFAULT:FALSE:FALSE:FALSE:0:DEFAULT:{}^swn_verify_auto_added_recommended_software_message_displayed_B^1^TRUE^sw_rs_5773_stg:new_maintenance^1^sw_core_nim_maint_3yr^SWN_EXPLICITLY_DELETED_MTMS^1^sw_rs_5608_pc2^
084657 924    19730       1ACGB       1ACGJ       1ACGV       2ACSR      16ADBE       2ADN1       1ADT4       9AHZE       1AKNC       1ALH0       1ALK3       1
954657924                   000000000            T           1                    20250319                                                    IBM FlashSystem 7300 NVMe Control Enclosure 
060600001MDDTIER_NEEDTOBETOTALED^1^YES^IBM_MTM_NAME^1^^SSD_RACK_CB^1^2^ibm_parent_id_S^1^SSD_Leaf_Category 0x000003A63F9803C0 [SBO_FLASH_SSD]^SSD_2076_DATA^1^ssd_4657_noexp^SHIPPING_FEATURECODE^1^AKNC^PASSWORD^1^FOR ECONFIG ADMIN USER ONLY^SERVICE_INTEGRATOR_RELATED_HW^1^4657924-1-28^IBM_MTM_CONTEXTS_MC^4^ssd_4657_924^ibm_region_ap^ibm_country_korea^ibm_INITIAL^SSD_MTM_EXPLICIT_SELECTION_QTYS_MF^10^1^0^2^16^0^1^0^9^1^1^SSD_MTM_EXPLICIT_SELECTION_MC^10^ssd_2076_AKNC^ssd_2076_AKCH^ssd_4664_ADBE^ssd_2076_ACSR^ssd_4657_ADSG^ssd_2076_AHZE^ssd_2076_AHZD_824^ssd_2076_ADT4^ssd_2076_ACGJ^ssd_2076_ACGB^
060042001BED1^1^01F3FFFFFC50^01F3FFFFFC50^
969730                                            Power Cord - PDU Connection                 
96ACGB                                            768 GB Cache upgrade                        
96ACGJ                                            512 GB Cache upgrade                        
96ACGV                      N                     240 GB M.2 Boot drive Pair                  
96ACSR                                            5m OM3 Fiber Cable (LC)                     
96ADBE                                            32 Gb FC 4 Port Adapter Cards (Pair)        
96ADN1                      N                     Order Type 1 Indicator - CTO                
96ADT4                                            7.68 TB NVMe Flash Drive                    
96AHZE                      N                     Hybrid Flash Indicator                      
96AKNC                                            Premium S&H Indicator                       
96ALH0                      N                     Expert Care Indicator                       
96ALK3                      N                     EC Advanced 3 Year                          
084658 A03    1
954658A03                   000000000            T           0                    20250319                                                    3 year IBM Storage Expert Care Advanced     
060119001MDDTIER_MAINTENANCEPRODUCT^1^YES^BASE_SERVICES_INTEGRATOR_TAG^1^^SERVICE_INTEGRATOR_RELATED_HW^1^4657924-1-28^
060041001BED1^^01F3FFFFFD80^01F3FFFFFD80^
475773STG    12000       1
955773STG                   000000000           NT           0                    20250319                                                    Support Line for Storage - 3 Year                           
060104001MDDSWN_MTM_CONTEXTS_MC^4^ibm_region_ap^ibm_country_korea^sw_software_p_series_type^ibm_INITIAL^
060042001BED1^3^01F3FFFFFCC0^01F3FFFFFCC0^
962000                      N                     Support per Server (N/C)                                    
98   43
993811517307
]]></CFReportBLOB>
  </CFData>
</CFXML>